### PR TITLE
Add initial code

### PR DESCRIPTION
**Pull request by alexgibson**
# Description

- Adds banner JS logic / tests.
- Adds banner SCSS/CSS.
- Adds webpack for building NPM package and local dev environment.
- Updates documentation.

## Testing

Start with `README.md` and take things from there.

- [x] Does everything install OK?
- [x] Do the docs make sense?
- [x] Does the demo / local dev page work correctly running `npm start`?
- [x] Does building the package using `npm run build` work OK?
- [x] Do the tests pass as expected running `npm test`?

### CODE REVIEW

**Review by stephaniehobson — CHANGES_REQUESTED** [review]

**Comment by stephaniehobson** [comment]
🦆 🦆 🦆 Ducks are all in a row. Just one blocking issue and a bunch of other thoughts that you are under no obligation to do if you are sick of looking at this code ;)

**Comment by alexgibson** [comment]
@stephaniehobson many thanks for the review - I pushed a commit with some fixes 👍

**Comment by alexgibson** [comment]
@stephaniehobson could you take a look and approve this PR if the updates look OK? Thank you

**Comment by stephaniehobson** [comment]
R+ 🦆

**Review by stephaniehobson — APPROVED** [review]

**Comment by stephaniehobson** [comment]
Leaving it for you to handle the squash and merge.

**Pull request merged**
